FROM node:18-slim

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci && npm cache clean --force
RUN npx prisma generate

COPY . .

ENV NODE_ENV=development

EXPOSE 3000

# Aspetta che MongoDB sia pronto prima di avviare
CMD ["npm", "run", "dev"]
