services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql://root:password@localhost:3306/dev
      MONGO_URL: mongodb://mongo:27017/devdb
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: 'unless-stopped'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  mongo-data:
    driver: local
